/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Body: typeof import('./../node_modules/@maizzle/framework/dist/components/Body.vue')['default']
    Button: typeof import('./../node_modules/@maizzle/framework/dist/components/Button.vue')['default']
    CodeBlock: typeof import('./../node_modules/@maizzle/framework/dist/components/CodeBlock.vue')['default']
    CodeInline: typeof import('./../node_modules/@maizzle/framework/dist/components/CodeInline.vue')['default']
    Column: typeof import('./../node_modules/@maizzle/framework/dist/components/Column.vue')['default']
    Container: typeof import('./../node_modules/@maizzle/framework/dist/components/Container.vue')['default']
    Divider: typeof import('./../node_modules/@maizzle/framework/dist/components/Divider.vue')['default']
    Head: typeof import('./../node_modules/@maizzle/framework/dist/components/Head.vue')['default']
    Html: typeof import('./../node_modules/@maizzle/framework/dist/components/Html.vue')['default']
    Image: typeof import('./../node_modules/@maizzle/framework/dist/components/Image.vue')['default']
    Markdown: typeof import('./../node_modules/@maizzle/framework/dist/components/Markdown.vue')['default']
    NotOutlook: typeof import('./../node_modules/@maizzle/framework/dist/components/NotOutlook.vue')['default']
    NoWidows: typeof import('./../node_modules/@maizzle/framework/dist/components/NoWidows.vue')['default']
    Outlook: typeof import('./../node_modules/@maizzle/framework/dist/components/Outlook.vue')['default']
    Overlap: typeof import('./../node_modules/@maizzle/framework/dist/components/Overlap.vue')['default']
    Preheader: typeof import('./../node_modules/@maizzle/framework/dist/components/Preheader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./../node_modules/@maizzle/framework/dist/components/Row.vue')['default']
    Spacer: typeof import('./../node_modules/@maizzle/framework/dist/components/Spacer.vue')['default']
    Vml: typeof import('./../node_modules/@maizzle/framework/dist/components/Vml.vue')['default']
    WithUrl: typeof import('./../node_modules/@maizzle/framework/dist/components/WithUrl.vue')['default']
  }
}
